/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.Ods.AdminApi.V2.Client.Client.OpenAPIDateConverter;

namespace EdFi.Ods.AdminApi.V2.Client.Model
{
    /// <summary>
    /// AuthorizationStrategy
    /// </summary>
    [DataContract(Name = "authorizationStrategy")]
    public partial class AuthorizationStrategy : IEquatable<AuthorizationStrategy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationStrategy" /> class.
        /// </summary>
        /// <param name="authStrategyId">authStrategyId.</param>
        /// <param name="authStrategyName">authStrategyName.</param>
        /// <param name="isInheritedFromParent">isInheritedFromParent.</param>
        public AuthorizationStrategy(int authStrategyId = default(int), string authStrategyName = default(string), bool isInheritedFromParent = default(bool))
        {
            this.AuthStrategyId = authStrategyId;
            this.AuthStrategyName = authStrategyName;
            this.IsInheritedFromParent = isInheritedFromParent;
        }

        /// <summary>
        /// Gets or Sets AuthStrategyId
        /// </summary>
        [DataMember(Name = "authStrategyId", EmitDefaultValue = false)]
        public int AuthStrategyId { get; set; }

        /// <summary>
        /// Gets or Sets AuthStrategyName
        /// </summary>
        [DataMember(Name = "authStrategyName", EmitDefaultValue = true)]
        public string AuthStrategyName { get; set; }

        /// <summary>
        /// Gets or Sets IsInheritedFromParent
        /// </summary>
        [DataMember(Name = "isInheritedFromParent", EmitDefaultValue = true)]
        public bool IsInheritedFromParent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthorizationStrategy {\n");
            sb.Append("  AuthStrategyId: ").Append(AuthStrategyId).Append("\n");
            sb.Append("  AuthStrategyName: ").Append(AuthStrategyName).Append("\n");
            sb.Append("  IsInheritedFromParent: ").Append(IsInheritedFromParent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthorizationStrategy);
        }

        /// <summary>
        /// Returns true if AuthorizationStrategy instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthorizationStrategy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthorizationStrategy input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AuthStrategyId == input.AuthStrategyId ||
                    this.AuthStrategyId.Equals(input.AuthStrategyId)
                ) && 
                (
                    this.AuthStrategyName == input.AuthStrategyName ||
                    (this.AuthStrategyName != null &&
                    this.AuthStrategyName.Equals(input.AuthStrategyName))
                ) && 
                (
                    this.IsInheritedFromParent == input.IsInheritedFromParent ||
                    this.IsInheritedFromParent.Equals(input.IsInheritedFromParent)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.AuthStrategyId.GetHashCode();
                if (this.AuthStrategyName != null)
                {
                    hashCode = (hashCode * 59) + this.AuthStrategyName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsInheritedFromParent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
