/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.Ods.AdminApi.V2.Client.Client.OpenAPIDateConverter;

namespace EdFi.Ods.AdminApi.V2.Client.Model
{
    /// <summary>
    /// EditOdsInstanceContextRequest
    /// </summary>
    [DataContract(Name = "editOdsInstanceContextRequest")]
    public partial class EditOdsInstanceContextRequest : IEquatable<EditOdsInstanceContextRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EditOdsInstanceContextRequest" /> class.
        /// </summary>
        /// <param name="odsInstanceId">ODS instance context ODS instance id..</param>
        /// <param name="contextKey">context key..</param>
        /// <param name="contextValue">context value..</param>
        public EditOdsInstanceContextRequest(int odsInstanceId = default(int), string contextKey = default(string), string contextValue = default(string))
        {
            this.OdsInstanceId = odsInstanceId;
            this.ContextKey = contextKey;
            this.ContextValue = contextValue;
        }

        /// <summary>
        /// ODS instance context ODS instance id.
        /// </summary>
        /// <value>ODS instance context ODS instance id.</value>
        [DataMember(Name = "odsInstanceId", EmitDefaultValue = false)]
        public int OdsInstanceId { get; set; }

        /// <summary>
        /// context key.
        /// </summary>
        /// <value>context key.</value>
        [DataMember(Name = "contextKey", EmitDefaultValue = false)]
        public string ContextKey { get; set; }

        /// <summary>
        /// context value.
        /// </summary>
        /// <value>context value.</value>
        [DataMember(Name = "contextValue", EmitDefaultValue = false)]
        public string ContextValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EditOdsInstanceContextRequest {\n");
            sb.Append("  OdsInstanceId: ").Append(OdsInstanceId).Append("\n");
            sb.Append("  ContextKey: ").Append(ContextKey).Append("\n");
            sb.Append("  ContextValue: ").Append(ContextValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EditOdsInstanceContextRequest);
        }

        /// <summary>
        /// Returns true if EditOdsInstanceContextRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of EditOdsInstanceContextRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EditOdsInstanceContextRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OdsInstanceId == input.OdsInstanceId ||
                    this.OdsInstanceId.Equals(input.OdsInstanceId)
                ) && 
                (
                    this.ContextKey == input.ContextKey ||
                    (this.ContextKey != null &&
                    this.ContextKey.Equals(input.ContextKey))
                ) && 
                (
                    this.ContextValue == input.ContextValue ||
                    (this.ContextValue != null &&
                    this.ContextValue.Equals(input.ContextValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.OdsInstanceId.GetHashCode();
                if (this.ContextKey != null)
                {
                    hashCode = (hashCode * 59) + this.ContextKey.GetHashCode();
                }
                if (this.ContextValue != null)
                {
                    hashCode = (hashCode * 59) + this.ContextValue.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
