trigger:
  branches:
    include:
      - EdGraph/v2.2.1-dev
  paths:
    include:
      - Client/admin-api-2.2.1/net8.0

pool:
  vmImage: "ubuntu-latest"

variables:
  majorVersion: "8"
  minorVersion: "0"
  revisionVersion: $[counter(variables['majorVersion'], 0)]
  nugetVersion: "$(majorVersion).$(minorVersion).$(revisionVersion).$(Build.BuildId)"

steps:
  # Prevent the global.json from overriding the .NET version
  - script: rm $(Build.SourcesDirectory)/global.json
    displayName: "Remove global.json"

  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.x"

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: "pack"
      packagesToPack: "$(Build.SourcesDirectory)/Client/admin-api-2.2.1/net8.0/src/EdFi.Ods.AdminApi.V2.Client/EdFi.Ods.AdminApi.V2.Client.csproj"
      versioningScheme: byEnvVar
      versionEnvVar: nugetVersion

  - task: DotNetCoreCLI@2
    displayName: "dotnet nuget push"
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "a373bb38-04b4-4f63-a889-e5ae2c46478d/8369284e-1702-4d6a-9075-69ff8e3ac69b"
