trigger:
  branches:
    include:
      - EdGraph/v2
      - EdGraph/v2-dev
  paths:
    include:
      - Application
      - Docker/edgraph.mssql.Dockerfile"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: DockerBuild
    condition: eq(variables['build.sourceBranch'], 'refs/heads/EdGraph/v2-dev')
    jobs:
      - job: "BuildAndPush"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: "eginfracrdevelopmentusc"

          - task: Docker@2
            displayName: "Build Docker Image"
            inputs:
              command: "build"
              Dockerfile: "$(Build.SourcesDirectory)/Docker/edgraph.mssql.Dockerfile"
              buildContext: "$(Build.SourcesDirectory)/Docker"
              arguments: "--build-context assets=$(Build.SourcesDirectory)"
              repository: "edfi/admin-api-v2"
              tags: |
                  $(Build.BuildNumber)
                  latest

          - task: Docker@2
            displayName: "Push Docker Image"
            inputs:
              command: "push"
              repository: "edfi/admin-api-v2"
              tags: |
                  $(Build.BuildNumber)
                  latest

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: eginfracrdevelopmentusc

  - stage: QADockerBuild
    condition: eq(variables['build.sourceBranch'], 'refs/heads/EdGraph/v2')
    jobs:
      - job: "BuildAndPush"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: "eginfracrqausc"

          - task: Docker@2
            displayName: "Build Docker Image"
            inputs:
              command: "build"
              Dockerfile: "$(Build.SourcesDirectory)/Docker/edgraph.mssql.Dockerfile"
              buildContext: "$(Build.SourcesDirectory)/Docker"
              arguments: "--build-context assets=$(Build.SourcesDirectory)"
              repository: "edfi/admin-api-v2"
              tags: |
                  $(Build.BuildNumber)
                  latest

          - task: Docker@2
            displayName: "Push Docker Image"
            inputs:
              command: "push"
              repository: "edfi/admin-api-v2"
              tags: |
                  $(Build.BuildNumber)
                  latest

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: eginfracrqausc

# trigger azure pipeline