trigger:
  branches:
    include:
      - EdGraph/v2.2.1-dev
  paths:
    include:
      - Client/admin-api-2.2.1
      - .azure/pipelines/admin-api-client-2.2.1.yml

pool:
  vmImage: "ubuntu-latest"

variables:
  majorVersion: "0"
  minorVersion: "1"
  revisionVersion: $[counter(variables['majorVersion'], 1)]
  nugetversion: "$(majorVersion).$(minorVersion).$(Build.BuildId).$(revisionVersion)"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.x"

  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: "restore"
      projects: "$(Build.SourcesDirectory)/Client/admin-api-2.2.1/src/EdFi.Ods.AdminApi.Client/EdFi.Ods.AdminApi.Client.csproj"
      feedsToUse: "select"
      vstsFeed: "a373bb38-04b4-4f63-a889-e5ae2c46478d/8369284e-1702-4d6a-9075-69ff8e3ac69b"

  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      command: "build"
      projects: "$(Build.SourcesDirectory)/Client/admin-api-2.2.1/src/EdFi.Ods.AdminApi.Client/EdFi.Ods.AdminApi.Client.csproj"
      arguments: "--configuration Release --no-restore -p:Version=$(majorVersion).$(minorVersion).$(Build.BuildId).$(revisionVersion)"

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: "pack"
      packagesToPack: "$(Build.SourcesDirectory)/Client/admin-api-2.2.1/src/EdFi.Ods.AdminApi.Client/EdFi.Ods.AdminApi.Client.csproj"
      versioningScheme: byEnvVar
      versionEnvVar: nugetversion

  - task: NuGetCommand@2
    displayName: "nuget push"
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "a373bb38-04b4-4f63-a889-e5ae2c46478d/8369284e-1702-4d6a-9075-69ff8e3ac69b"
      # allowPackageConflicts: true # TODO Is this needed?
