trigger:
  - EdGraph/v2.2.1-dev

pool:
  vmImage: "ubuntu-latest"

variables:
  # - name: buildConfiguration
  #   value: "Release"
  # - group: 'Shared DevOps Variables'
  - name: RunBuildAndPush
    value: "false" # TODO Enable this when ready to build and push Docker image
  - name: RunPublishApiClientNugetPackage
    value: "true"

stages:
  - stage: DockerBuild
    condition: eq(variables['build.sourceBranch'], 'refs/heads/EdGraph/v2.2.1-dev')
    jobs:
      - job: "BuildAndPush"
        condition: eq(variables['RunBuildAndPush'], 'true')
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: "eginfracrdevelopmentusc"

          - task: Docker@2
            displayName: "Build Docker Image"
            inputs:
              command: "build"
              Dockerfile: "$(Build.SourcesDirectory)/Docker/edgraph.mssql.Dockerfile"
              buildContext: "$(Build.SourcesDirectory)/Docker"
              arguments: "--build-context assets=$(Build.SourcesDirectory)"
              repository: "edfi/admin-api-v2"
              tags: |
                  $(Build.BuildNumber)
                  latest

          - task: Docker@2
            displayName: "Push Docker Image"
            inputs:
              command: "push"
              repository: "edfi/admin-api-v2"
              tags: |
                  $(Build.BuildNumber)
                  latest

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: eginfracrdevelopmentusc
      
      - job: "PublishApiClientNugetPackage"
        condition: eq(variables['RunPublishApiClientNugetPackage'], 'true')
        steps:
          - checkout: self
            # persistCredentials: true # TODO Is this needed?
          
          # For more information about UseDotNet@2 see:
          # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines
          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "8.x"
              # useGlobalJson: true
              # workingDirectory: "$(Build.SourcesDirectory)"
          
          - task: DotNetCoreCLI@2
            displayName: "dotnet clean"
            inputs:
              command: "custom"
              custom: "clean"
              arguments: "$(Build.SourcesDirectory)/Application --configuration Release --nologo --verbosity minimal"
          
          - script: dotnet --version
            displayName: "Display .NET Version"
          
          - script: echo $(Build.SourcesDirectory)
            displayName: "Display Build Sources Directory"

          - script: ls -la $(Build.SourcesDirectory)
            displayName: "List Build Sources Directory"
          
          - script: cat $(Build.SourcesDirectory)/Application/NuGet.Config
            displayName: "Display NuGet.Config"

          - script: dotnet restore $(Build.SourcesDirectory)/Application
            displayName: "dotnet restore"
            # inputs:
            #   command: "restore"
            #   projects: "$(Build.SourcesDirectory)/Application"
            #   # Feeds and authentication
            #   feedsToUse: "select" # 'select' | 'config'. Alias: selectOrConfig. Required when command = restore. Feeds to use. Default: select.
            #   #vstsFeed: # string. Alias: feedRestore. Optional. Use when selectOrConfig = select && command = restore. Use packages from this Azure Artifacts feed. Select from the dropdown or enter [project name/]feed name.
            #   includeNuGetOrg: true # boolean. Optional. Use when selectOrConfig = select && command = restore. Use packages from NuGet.org. Default: true.
            #   nugetConfigPath: "$(Build.SourcesDirectory)/Application/NuGet.Config" # string. Optional. Use when selectOrConfig = config && command = restore. Path to NuGet.config. 
            #   #externalFeedCredentials: # string. Alias: externalEndpoints. Optional. Use when selectOrConfig = config && command = restore. Credentials for feeds outside this organization/collection.
          
          - task: DotNetCoreCLI@2
            displayName: "dotnet tool restore"
            inputs:
              command: "custom"
              custom: "tool restore"
              arguments: "--tool-manifest $(Build.SourcesDirectory)/.config/dotnet-tools.json"
          
          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: "build"
              projects: "$(Build.SourcesDirectory)/Application"
              arguments: "--configuration Release --no-restore"
          
          - task: DotNetCoreCLI@2
            displayName: "dotnet tool run swagger tofile"
            inputs:
              command: "custom"
              custom: "tool run swagger tofile"
              arguments: "--output $(Build.SourcesDirectory)/tmp/openapi.yml --yaml $(Build.SourcesDirectory)/tmp/EdFi.Ods.AdminApi.dll v2"
          
          - script: cat $(Build.SourcesDirectory)/tmp/openapi.yml
            displayName: "Display OpenAPI YAML"
