// <auto-generated>
/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.Ods.AdminApi.Client.Client;

namespace EdFi.Ods.AdminApi.Client.Model
{
    /// <summary>
    /// ClaimSetResourceClaimModel
    /// </summary>
    public partial class ClaimSetResourceClaimModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClaimSetResourceClaimModel" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="actions">actions</param>
        /// <param name="defaultAuthorizationStrategiesForCRUD">defaultAuthorizationStrategiesForCRUD</param>
        /// <param name="authorizationStrategyOverridesForCRUD">authorizationStrategyOverridesForCRUD</param>
        /// <param name="children">Children are collection of ResourceClaim</param>
        [JsonConstructor]
        public ClaimSetResourceClaimModel(Option<int?> id = default, Option<string> name = default, Option<List<ResourceClaimAction>> actions = default, Option<List<ClaimSetResourceClaimActionAuthStrategies>> defaultAuthorizationStrategiesForCRUD = default, Option<List<ClaimSetResourceClaimActionAuthStrategies>> authorizationStrategyOverridesForCRUD = default, Option<List<ClaimSetResourceClaimModel>> children = default)
        {
            IdOption = id;
            NameOption = name;
            ActionsOption = actions;
            DefaultAuthorizationStrategiesForCRUDOption = defaultAuthorizationStrategiesForCRUD;
            AuthorizationStrategyOverridesForCRUDOption = authorizationStrategyOverridesForCRUD;
            ChildrenOption = children;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption; } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Actions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ResourceClaimAction>> ActionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Actions
        /// </summary>
        [JsonPropertyName("actions")]
        public List<ResourceClaimAction> Actions { get { return this.ActionsOption; } set { this.ActionsOption = new Option<List<ResourceClaimAction>>(value); } }

        /// <summary>
        /// Used to track the state of DefaultAuthorizationStrategiesForCRUD
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ClaimSetResourceClaimActionAuthStrategies>> DefaultAuthorizationStrategiesForCRUDOption { get; }

        /// <summary>
        /// Gets or Sets DefaultAuthorizationStrategiesForCRUD
        /// </summary>
        [JsonPropertyName("_defaultAuthorizationStrategiesForCRUD")]
        public List<ClaimSetResourceClaimActionAuthStrategies> DefaultAuthorizationStrategiesForCRUD { get { return this.DefaultAuthorizationStrategiesForCRUDOption; } }

        /// <summary>
        /// Used to track the state of AuthorizationStrategyOverridesForCRUD
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ClaimSetResourceClaimActionAuthStrategies>> AuthorizationStrategyOverridesForCRUDOption { get; private set; }

        /// <summary>
        /// Gets or Sets AuthorizationStrategyOverridesForCRUD
        /// </summary>
        [JsonPropertyName("authorizationStrategyOverridesForCRUD")]
        public List<ClaimSetResourceClaimActionAuthStrategies> AuthorizationStrategyOverridesForCRUD { get { return this.AuthorizationStrategyOverridesForCRUDOption; } set { this.AuthorizationStrategyOverridesForCRUDOption = new Option<List<ClaimSetResourceClaimActionAuthStrategies>>(value); } }

        /// <summary>
        /// Used to track the state of Children
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ClaimSetResourceClaimModel>> ChildrenOption { get; private set; }

        /// <summary>
        /// Children are collection of ResourceClaim
        /// </summary>
        /// <value>Children are collection of ResourceClaim</value>
        [JsonPropertyName("children")]
        public List<ClaimSetResourceClaimModel> Children { get { return this.ChildrenOption; } set { this.ChildrenOption = new Option<List<ClaimSetResourceClaimModel>>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClaimSetResourceClaimModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Actions: ").Append(Actions).Append("\n");
            sb.Append("  DefaultAuthorizationStrategiesForCRUD: ").Append(DefaultAuthorizationStrategiesForCRUD).Append("\n");
            sb.Append("  AuthorizationStrategyOverridesForCRUD: ").Append(AuthorizationStrategyOverridesForCRUD).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ClaimSetResourceClaimModel" />
    /// </summary>
    public class ClaimSetResourceClaimModelJsonConverter : JsonConverter<ClaimSetResourceClaimModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="ClaimSetResourceClaimModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ClaimSetResourceClaimModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string> name = default;
            Option<List<ResourceClaimAction>> actions = default;
            Option<List<ClaimSetResourceClaimActionAuthStrategies>> defaultAuthorizationStrategiesForCRUD = default;
            Option<List<ClaimSetResourceClaimActionAuthStrategies>> authorizationStrategyOverridesForCRUD = default;
            Option<List<ClaimSetResourceClaimModel>> children = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "actions":
                            actions = new Option<List<ResourceClaimAction>>(JsonSerializer.Deserialize<List<ResourceClaimAction>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "_defaultAuthorizationStrategiesForCRUD":
                            defaultAuthorizationStrategiesForCRUD = new Option<List<ClaimSetResourceClaimActionAuthStrategies>>(JsonSerializer.Deserialize<List<ClaimSetResourceClaimActionAuthStrategies>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "authorizationStrategyOverridesForCRUD":
                            authorizationStrategyOverridesForCRUD = new Option<List<ClaimSetResourceClaimActionAuthStrategies>>(JsonSerializer.Deserialize<List<ClaimSetResourceClaimActionAuthStrategies>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "children":
                            children = new Option<List<ClaimSetResourceClaimModel>>(JsonSerializer.Deserialize<List<ClaimSetResourceClaimModel>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ClaimSetResourceClaimModel.");

            return new ClaimSetResourceClaimModel(id, name, actions, defaultAuthorizationStrategiesForCRUD, authorizationStrategyOverridesForCRUD, children);
        }

        /// <summary>
        /// Serializes a <see cref="ClaimSetResourceClaimModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="claimSetResourceClaimModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ClaimSetResourceClaimModel claimSetResourceClaimModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, claimSetResourceClaimModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ClaimSetResourceClaimModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="claimSetResourceClaimModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ClaimSetResourceClaimModel claimSetResourceClaimModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (claimSetResourceClaimModel.IdOption.IsSet)
                writer.WriteNumber("id", claimSetResourceClaimModel.IdOption.Value.Value);

            if (claimSetResourceClaimModel.NameOption.IsSet)
                if (claimSetResourceClaimModel.NameOption.Value != null)
                    writer.WriteString("name", claimSetResourceClaimModel.Name);
                else
                    writer.WriteNull("name");

            if (claimSetResourceClaimModel.ActionsOption.IsSet)
                if (claimSetResourceClaimModel.ActionsOption.Value != null)
                {
                    writer.WritePropertyName("actions");
                    JsonSerializer.Serialize(writer, claimSetResourceClaimModel.Actions, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("actions");
            if (claimSetResourceClaimModel.DefaultAuthorizationStrategiesForCRUDOption.IsSet)
                if (claimSetResourceClaimModel.DefaultAuthorizationStrategiesForCRUDOption.Value != null)
                {
                    writer.WritePropertyName("_defaultAuthorizationStrategiesForCRUD");
                    JsonSerializer.Serialize(writer, claimSetResourceClaimModel.DefaultAuthorizationStrategiesForCRUD, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("_defaultAuthorizationStrategiesForCRUD");
            if (claimSetResourceClaimModel.AuthorizationStrategyOverridesForCRUDOption.IsSet)
                if (claimSetResourceClaimModel.AuthorizationStrategyOverridesForCRUDOption.Value != null)
                {
                    writer.WritePropertyName("authorizationStrategyOverridesForCRUD");
                    JsonSerializer.Serialize(writer, claimSetResourceClaimModel.AuthorizationStrategyOverridesForCRUD, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("authorizationStrategyOverridesForCRUD");
            if (claimSetResourceClaimModel.ChildrenOption.IsSet)
                if (claimSetResourceClaimModel.ChildrenOption.Value != null)
                {
                    writer.WritePropertyName("children");
                    JsonSerializer.Serialize(writer, claimSetResourceClaimModel.Children, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("children");
        }
    }
}
