// <auto-generated>
/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.Ods.AdminApi.Client.Client;

namespace EdFi.Ods.AdminApi.Client.Model
{
    /// <summary>
    /// CopyClaimSetRequest
    /// </summary>
    public partial class CopyClaimSetRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CopyClaimSetRequest" /> class.
        /// </summary>
        /// <param name="originalId">ClaimSet id to copy</param>
        /// <param name="name">New claimset name</param>
        [JsonConstructor]
        public CopyClaimSetRequest(Option<int?> originalId = default, Option<string> name = default)
        {
            OriginalIdOption = originalId;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OriginalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OriginalIdOption { get; private set; }

        /// <summary>
        /// ClaimSet id to copy
        /// </summary>
        /// <value>ClaimSet id to copy</value>
        [JsonPropertyName("originalId")]
        public int? OriginalId { get { return this.OriginalIdOption; } set { this.OriginalIdOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// New claimset name
        /// </summary>
        /// <value>New claimset name</value>
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CopyClaimSetRequest {\n");
            sb.Append("  OriginalId: ").Append(OriginalId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CopyClaimSetRequest" />
    /// </summary>
    public class CopyClaimSetRequestJsonConverter : JsonConverter<CopyClaimSetRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CopyClaimSetRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CopyClaimSetRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> originalId = default;
            Option<string> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "originalId":
                            originalId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (originalId.IsSet && originalId.Value == null)
                throw new ArgumentNullException(nameof(originalId), "Property is not nullable for class CopyClaimSetRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CopyClaimSetRequest.");

            return new CopyClaimSetRequest(originalId, name);
        }

        /// <summary>
        /// Serializes a <see cref="CopyClaimSetRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="copyClaimSetRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CopyClaimSetRequest copyClaimSetRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, copyClaimSetRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CopyClaimSetRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="copyClaimSetRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CopyClaimSetRequest copyClaimSetRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (copyClaimSetRequest.NameOption.IsSet && copyClaimSetRequest.Name == null)
                throw new ArgumentNullException(nameof(copyClaimSetRequest.Name), "Property is required for class CopyClaimSetRequest.");

            if (copyClaimSetRequest.OriginalIdOption.IsSet)
                writer.WriteNumber("originalId", copyClaimSetRequest.OriginalIdOption.Value.Value);

            if (copyClaimSetRequest.NameOption.IsSet)
                writer.WriteString("name", copyClaimSetRequest.Name);
        }
    }
}
