// <auto-generated>
/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.Ods.AdminApi.Client.Client;

namespace EdFi.Ods.AdminApi.Client.Model
{
    /// <summary>
    /// EditOdsInstanceRequest
    /// </summary>
    public partial class EditOdsInstanceRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EditOdsInstanceRequest" /> class.
        /// </summary>
        /// <param name="name">Ods Instance name</param>
        /// <param name="instanceType">Ods Instance type</param>
        /// <param name="connectionString">Ods Instance connection string</param>
        [JsonConstructor]
        public EditOdsInstanceRequest(Option<string?> name = default, Option<string?> instanceType = default, Option<string?> connectionString = default)
        {
            NameOption = name;
            InstanceTypeOption = instanceType;
            ConnectionStringOption = connectionString;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Ods Instance name
        /// </summary>
        /// <value>Ods Instance name</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of InstanceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceTypeOption { get; private set; }

        /// <summary>
        /// Ods Instance type
        /// </summary>
        /// <value>Ods Instance type</value>
        [JsonPropertyName("instanceType")]
        public string? InstanceType { get { return this.InstanceTypeOption; } set { this.InstanceTypeOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ConnectionString
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConnectionStringOption { get; private set; }

        /// <summary>
        /// Ods Instance connection string
        /// </summary>
        /// <value>Ods Instance connection string</value>
        [JsonPropertyName("connectionString")]
        public string? ConnectionString { get { return this.ConnectionStringOption; } set { this.ConnectionStringOption = new Option<string?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EditOdsInstanceRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  InstanceType: ").Append(InstanceType).Append("\n");
            sb.Append("  ConnectionString: ").Append(ConnectionString).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EditOdsInstanceRequest" />
    /// </summary>
    public class EditOdsInstanceRequestJsonConverter : JsonConverter<EditOdsInstanceRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="EditOdsInstanceRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EditOdsInstanceRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> instanceType = default;
            Option<string?> connectionString = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "instanceType":
                            instanceType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "connectionString":
                            connectionString = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class EditOdsInstanceRequest.");

            return new EditOdsInstanceRequest(name, instanceType, connectionString);
        }

        /// <summary>
        /// Serializes a <see cref="EditOdsInstanceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="editOdsInstanceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EditOdsInstanceRequest editOdsInstanceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, editOdsInstanceRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EditOdsInstanceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="editOdsInstanceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EditOdsInstanceRequest editOdsInstanceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (editOdsInstanceRequest.NameOption.IsSet && editOdsInstanceRequest.Name == null)
                throw new ArgumentNullException(nameof(editOdsInstanceRequest.Name), "Property is required for class EditOdsInstanceRequest.");

            if (editOdsInstanceRequest.NameOption.IsSet)
                writer.WriteString("name", editOdsInstanceRequest.Name);

            if (editOdsInstanceRequest.InstanceTypeOption.IsSet)
                if (editOdsInstanceRequest.InstanceTypeOption.Value != null)
                    writer.WriteString("instanceType", editOdsInstanceRequest.InstanceType);
                else
                    writer.WriteNull("instanceType");

            if (editOdsInstanceRequest.ConnectionStringOption.IsSet)
                if (editOdsInstanceRequest.ConnectionStringOption.Value != null)
                    writer.WriteString("connectionString", editOdsInstanceRequest.ConnectionString);
                else
                    writer.WriteNull("connectionString");
        }
    }
}
