// <auto-generated>
/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.Ods.AdminApi.Client.Client;

namespace EdFi.Ods.AdminApi.Client.Model
{
    /// <summary>
    /// EditOdsInstanceDerivativeRequest
    /// </summary>
    public partial class EditOdsInstanceDerivativeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EditOdsInstanceDerivativeRequest" /> class.
        /// </summary>
        /// <param name="odsInstanceId">ODS instance derivative ODS instance id.</param>
        /// <param name="derivativeType">derivative type.</param>
        /// <param name="connectionString">connection string.</param>
        [JsonConstructor]
        public EditOdsInstanceDerivativeRequest(Option<int?> odsInstanceId = default, Option<string?> derivativeType = default, Option<string?> connectionString = default)
        {
            OdsInstanceIdOption = odsInstanceId;
            DerivativeTypeOption = derivativeType;
            ConnectionStringOption = connectionString;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OdsInstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OdsInstanceIdOption { get; private set; }

        /// <summary>
        /// ODS instance derivative ODS instance id.
        /// </summary>
        /// <value>ODS instance derivative ODS instance id.</value>
        [JsonPropertyName("odsInstanceId")]
        public int? OdsInstanceId { get { return this.OdsInstanceIdOption; } set { this.OdsInstanceIdOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of DerivativeType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DerivativeTypeOption { get; private set; }

        /// <summary>
        /// derivative type.
        /// </summary>
        /// <value>derivative type.</value>
        [JsonPropertyName("derivativeType")]
        public string? DerivativeType { get { return this.DerivativeTypeOption; } set { this.DerivativeTypeOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ConnectionString
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConnectionStringOption { get; private set; }

        /// <summary>
        /// connection string.
        /// </summary>
        /// <value>connection string.</value>
        [JsonPropertyName("connectionString")]
        public string? ConnectionString { get { return this.ConnectionStringOption; } set { this.ConnectionStringOption = new Option<string?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EditOdsInstanceDerivativeRequest {\n");
            sb.Append("  OdsInstanceId: ").Append(OdsInstanceId).Append("\n");
            sb.Append("  DerivativeType: ").Append(DerivativeType).Append("\n");
            sb.Append("  ConnectionString: ").Append(ConnectionString).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EditOdsInstanceDerivativeRequest" />
    /// </summary>
    public class EditOdsInstanceDerivativeRequestJsonConverter : JsonConverter<EditOdsInstanceDerivativeRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="EditOdsInstanceDerivativeRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EditOdsInstanceDerivativeRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> odsInstanceId = default;
            Option<string?> derivativeType = default;
            Option<string?> connectionString = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "odsInstanceId":
                            odsInstanceId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "derivativeType":
                            derivativeType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "connectionString":
                            connectionString = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (odsInstanceId.IsSet && odsInstanceId.Value == null)
                throw new ArgumentNullException(nameof(odsInstanceId), "Property is not nullable for class EditOdsInstanceDerivativeRequest.");

            if (derivativeType.IsSet && derivativeType.Value == null)
                throw new ArgumentNullException(nameof(derivativeType), "Property is not nullable for class EditOdsInstanceDerivativeRequest.");

            if (connectionString.IsSet && connectionString.Value == null)
                throw new ArgumentNullException(nameof(connectionString), "Property is not nullable for class EditOdsInstanceDerivativeRequest.");

            return new EditOdsInstanceDerivativeRequest(odsInstanceId, derivativeType, connectionString);
        }

        /// <summary>
        /// Serializes a <see cref="EditOdsInstanceDerivativeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="editOdsInstanceDerivativeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EditOdsInstanceDerivativeRequest editOdsInstanceDerivativeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, editOdsInstanceDerivativeRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EditOdsInstanceDerivativeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="editOdsInstanceDerivativeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EditOdsInstanceDerivativeRequest editOdsInstanceDerivativeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (editOdsInstanceDerivativeRequest.DerivativeTypeOption.IsSet && editOdsInstanceDerivativeRequest.DerivativeType == null)
                throw new ArgumentNullException(nameof(editOdsInstanceDerivativeRequest.DerivativeType), "Property is required for class EditOdsInstanceDerivativeRequest.");

            if (editOdsInstanceDerivativeRequest.ConnectionStringOption.IsSet && editOdsInstanceDerivativeRequest.ConnectionString == null)
                throw new ArgumentNullException(nameof(editOdsInstanceDerivativeRequest.ConnectionString), "Property is required for class EditOdsInstanceDerivativeRequest.");

            if (editOdsInstanceDerivativeRequest.OdsInstanceIdOption.IsSet)
                writer.WriteNumber("odsInstanceId", editOdsInstanceDerivativeRequest.OdsInstanceIdOption.Value!.Value);

            if (editOdsInstanceDerivativeRequest.DerivativeTypeOption.IsSet)
                writer.WriteString("derivativeType", editOdsInstanceDerivativeRequest.DerivativeType);

            if (editOdsInstanceDerivativeRequest.ConnectionStringOption.IsSet)
                writer.WriteString("connectionString", editOdsInstanceDerivativeRequest.ConnectionString);
        }
    }
}
