// <auto-generated>
/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.Ods.AdminApi.Client.Client;

namespace EdFi.Ods.AdminApi.Client.Model
{
    /// <summary>
    /// OdsInstanceContextModel
    /// </summary>
    public partial class OdsInstanceContextModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OdsInstanceContextModel" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="odsInstanceId">odsInstanceId</param>
        /// <param name="contextKey">contextKey</param>
        /// <param name="contextValue">contextValue</param>
        [JsonConstructor]
        public OdsInstanceContextModel(Option<int?> id = default, Option<int?> odsInstanceId = default, Option<string?> contextKey = default, Option<string?> contextValue = default)
        {
            IdOption = id;
            OdsInstanceIdOption = odsInstanceId;
            ContextKeyOption = contextKey;
            ContextValueOption = contextValue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption; } set { this.IdOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of OdsInstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OdsInstanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OdsInstanceId
        /// </summary>
        [JsonPropertyName("odsInstanceId")]
        public int? OdsInstanceId { get { return this.OdsInstanceIdOption; } set { this.OdsInstanceIdOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of ContextKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContextKeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContextKey
        /// </summary>
        [JsonPropertyName("contextKey")]
        public string? ContextKey { get { return this.ContextKeyOption; } set { this.ContextKeyOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ContextValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContextValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContextValue
        /// </summary>
        [JsonPropertyName("contextValue")]
        public string? ContextValue { get { return this.ContextValueOption; } set { this.ContextValueOption = new Option<string?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OdsInstanceContextModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OdsInstanceId: ").Append(OdsInstanceId).Append("\n");
            sb.Append("  ContextKey: ").Append(ContextKey).Append("\n");
            sb.Append("  ContextValue: ").Append(ContextValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OdsInstanceContextModel" />
    /// </summary>
    public class OdsInstanceContextModelJsonConverter : JsonConverter<OdsInstanceContextModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="OdsInstanceContextModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OdsInstanceContextModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<int?> odsInstanceId = default;
            Option<string?> contextKey = default;
            Option<string?> contextValue = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "odsInstanceId":
                            odsInstanceId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "contextKey":
                            contextKey = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contextValue":
                            contextValue = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OdsInstanceContextModel.");

            if (odsInstanceId.IsSet && odsInstanceId.Value == null)
                throw new ArgumentNullException(nameof(odsInstanceId), "Property is not nullable for class OdsInstanceContextModel.");

            return new OdsInstanceContextModel(id, odsInstanceId, contextKey, contextValue);
        }

        /// <summary>
        /// Serializes a <see cref="OdsInstanceContextModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="odsInstanceContextModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OdsInstanceContextModel odsInstanceContextModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, odsInstanceContextModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OdsInstanceContextModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="odsInstanceContextModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OdsInstanceContextModel odsInstanceContextModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (odsInstanceContextModel.IdOption.IsSet)
                writer.WriteNumber("id", odsInstanceContextModel.IdOption.Value!.Value);

            if (odsInstanceContextModel.OdsInstanceIdOption.IsSet)
                writer.WriteNumber("odsInstanceId", odsInstanceContextModel.OdsInstanceIdOption.Value!.Value);

            if (odsInstanceContextModel.ContextKeyOption.IsSet)
                if (odsInstanceContextModel.ContextKeyOption.Value != null)
                    writer.WriteString("contextKey", odsInstanceContextModel.ContextKey);
                else
                    writer.WriteNull("contextKey");

            if (odsInstanceContextModel.ContextValueOption.IsSet)
                if (odsInstanceContextModel.ContextValueOption.Value != null)
                    writer.WriteString("contextValue", odsInstanceContextModel.ContextValue);
                else
                    writer.WriteNull("contextValue");
        }
    }
}
