// <auto-generated>
/*
 * Admin API Documentation
 *
 * The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.Ods.AdminApi.Client.Client;

namespace EdFi.Ods.AdminApi.Client.Model
{
    /// <summary>
    /// OdsInstanceDerivativeModel
    /// </summary>
    public partial class OdsInstanceDerivativeModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OdsInstanceDerivativeModel" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="odsInstanceId">odsInstanceId</param>
        /// <param name="derivativeType">derivativeType</param>
        [JsonConstructor]
        public OdsInstanceDerivativeModel(Option<int?> id = default, Option<int?> odsInstanceId = default, Option<string> derivativeType = default)
        {
            IdOption = id;
            OdsInstanceIdOption = odsInstanceId;
            DerivativeTypeOption = derivativeType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption; } set { this.IdOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of OdsInstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OdsInstanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OdsInstanceId
        /// </summary>
        [JsonPropertyName("odsInstanceId")]
        public int? OdsInstanceId { get { return this.OdsInstanceIdOption; } set { this.OdsInstanceIdOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of DerivativeType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DerivativeTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets DerivativeType
        /// </summary>
        [JsonPropertyName("derivativeType")]
        public string DerivativeType { get { return this.DerivativeTypeOption; } set { this.DerivativeTypeOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OdsInstanceDerivativeModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OdsInstanceId: ").Append(OdsInstanceId).Append("\n");
            sb.Append("  DerivativeType: ").Append(DerivativeType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OdsInstanceDerivativeModel" />
    /// </summary>
    public class OdsInstanceDerivativeModelJsonConverter : JsonConverter<OdsInstanceDerivativeModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="OdsInstanceDerivativeModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OdsInstanceDerivativeModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<int?> odsInstanceId = default;
            Option<string> derivativeType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "odsInstanceId":
                            odsInstanceId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "derivativeType":
                            derivativeType = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OdsInstanceDerivativeModel.");

            return new OdsInstanceDerivativeModel(id, odsInstanceId, derivativeType);
        }

        /// <summary>
        /// Serializes a <see cref="OdsInstanceDerivativeModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="odsInstanceDerivativeModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OdsInstanceDerivativeModel odsInstanceDerivativeModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, odsInstanceDerivativeModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OdsInstanceDerivativeModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="odsInstanceDerivativeModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OdsInstanceDerivativeModel odsInstanceDerivativeModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (odsInstanceDerivativeModel.IdOption.IsSet)
                writer.WriteNumber("id", odsInstanceDerivativeModel.IdOption.Value.Value);

            if (odsInstanceDerivativeModel.OdsInstanceIdOption.IsSet)
                if (odsInstanceDerivativeModel.OdsInstanceIdOption.Value != null)
                    writer.WriteNumber("odsInstanceId", odsInstanceDerivativeModel.OdsInstanceIdOption.Value.Value);
                else
                    writer.WriteNull("odsInstanceId");

            if (odsInstanceDerivativeModel.DerivativeTypeOption.IsSet)
                if (odsInstanceDerivativeModel.DerivativeTypeOption.Value != null)
                    writer.WriteString("derivativeType", odsInstanceDerivativeModel.DerivativeType);
                else
                    writer.WriteNull("derivativeType");
        }
    }
}
